version: '3.8'

services:
  backend-admin:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5001"

  frontend-admin:
    build:
      context: ./frontend  # Важно: контекст - папка frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"

networks:
  rocket-network-admin:
    driver: bridge