version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5000"

  frontend:
    build:
      context: ./frontend  # Важно: контекст - папка frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3000"

networks:
  rocket-network:
    driver: bridge